# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: CPP
descriptor_label: "C++"
descriptor_type: language
descriptor_flavors:
  - cit
file_extensions:
  - ".cpp"
  - ".h"
  - ".cc"
  - ".hpp"
  - ".cxx"
  - ".cu"
  - ".hxx"
  - ".c++"
  - ".hh"
  - ".h++"
  - ".cuh"
linters:
  # CLANG_FORMAT_16
  - linter_name: clang-format-16
    name: CPP_CLANG_FORMAT_16
    linter_url: https://clang.llvm.org/docs/ClangFormat.html
    linter_rules_url: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
    cli_lint_mode: list_of_files
    cli_help_arg_name: "--help"
    cli_version_arg_name: "--version"
    cli_lint_extra_args:
      - "--dry-run"
      - "--Werror"
    cli_lint_fix_remove_args:
      - "--dry-run"
      - "--Werror"
    cli_lint_fix_arg_name: "-i"
    cli_lint_errors_count: regex_count
    cli_lint_errors_regex: "code should be clang-formatted"
    examples:
      - "clang-format my_file.cpp"
    install:
      dockerfile:
        - RUN echo "is not implemented"
