# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: CPP
descriptor_label: "C++"
descriptor_type: language
descriptor_flavors:
  - cit
file_extensions:
  - ".cpp"
  - ".h"
  - ".cc"
  - ".hpp"
  - ".cxx"
  - ".cu"
  - ".hxx"
  - ".c++"
  - ".hh"
  - ".h++"
  - ".cuh"
linters:
  # CLANG_TIDY
  - linter_name: clang-tidy
    cli_executable: run-clang-tidy-16
    linter_url: https://clang.llvm.org/extra/clang-tidy
    linter_rules_url: https://clang.llvm.org/extra/clang-tidy/checks/list.html
    cli_lint_mode: list_of_files
    cli_help_arg_name: "--help"
    cli_version_arg_name: "--version"
    cli_executable_version: clang-tidy-16
    cli_lint_errors_count: regex_count
    cli_lint_errors_regex: "-warnings-as-errors"
    processing_order: -9
    examples:
      - "run-clang-tidy-16 test_1.cpp test_2.cpp"
    install:
      dockerfile:
        - RUN echo "is not implemented"
