# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: GIT
descriptor_type: other
descriptor_flavors:
  - cit
install:
  dockerfile:
    - RUN echo "is not implemented"
linters:
  # COMMITLINT
  - linter_name: commitlint
    lint_all_files: true
    linter_text: Lint commit messages
    linter_repo: https://github.com/conventional-changelog/commitlint
    cli_config_arg_name: "--config"
    config_file_name: ".commitlintrc.js"
    cli_executable: commitlint
    cli_lint_mode: project
    cli_help_arg_name: "--help"
    cli_version_arg_name: "--version"
    cli_lint_errors_count: regex_sum
    cli_lint_errors_regex: "found ([0-9]+) problems"
    examples:
      - "commitlint --to HEAD"
