# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: GIT
descriptor_type: other
descriptor_flavors:
  - cit
install:
  dockerfile:
    - RUN echo "is not implemented"
linters:
  # GIT_SIZER
  - linter_name: git_sizer
    lint_all_files: true
    linter_text: Compute various size metrics for a Git repository,
      flagging those that might cause problems
    linter_url: https://git-scm.com
    linter_repo: https://github.com/github/git-sizer
    linter_megalinter_ref_url: never
    cli_config_arg_name: ""
    cli_executable: git-sizer
    cli_lint_mode: project
    cli_help_arg_name: "--help"
    help_command_return_code: 1
    linter_version_cache: "1.5.0"
    examples:
      - "git-sizer"
