# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: GIT
descriptor_type: other
descriptor_flavors:
  - cit
lint_all_files: true
linters:
  # GIT_SPELL
  - linter_name: git-spell
    name: GIT_GIT_SPELL
    linter_text: |
      Checks spelling in git messages
    cli_lint_mode: project
    cli_executable: git-spell
    cli_executable_help: git
    cli_executable_version: git
    cli_help_arg_name: "--help"
    cli_config_arg_name: "--config"
    config_file_name: "cspell.json"
    examples:
      - "git-spell"
    install:
      dockerfile:
        - RUN echo "is not implemented"
