# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
descriptor_id: GIT
descriptor_type: other
descriptor_flavors:
  - cit
install:
  dockerfile:
    - RUN echo "is not implemented"
linters:
  # GITLINT
  - linter_name: gitlint
    lint_all_files: true
    linter_text: Git lint tool, checks your git commit messages for
      styling issues
    linter_repo: https://github.com/jorisroovers/gitlint
    cli_config_arg_name: "--config"
    cli_executable: gitlint
    cli_lint_mode: project
    cli_help_arg_name: "--help"
    cli_version_arg_name: "--version"
    cli_lint_errors_count: regex_count
    cli_lint_errors_regex: "([0-9]+): "
    examples:
      - "gitlint --commits HEAD"
