# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl }:

self: super: {
  "Mako" = super.buildPythonPackage rec {
    pname = "Mako";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/01/45ab9f723a93e0ca75fba4d2c266bb041120cb4215eab94f7c78743ac7ed/Mako-1.2.0-py3-none-any.whl";
      sha256 = "1fp4awp14xcn472f3v2awfc7x4zz4f1sb4rpp58i03xvvcgv3ai3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz";
      sha256 = "0jqxp5sfrc0byp6bk0gwdmildi4mck2gprp42afri3z4r5y1k4bz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "5.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz";
      sha256 = "0pm440pmpvgv5rbbnm8hk4qga5a292kvlm1bh3x2nwr8pb5p8xv0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "alembic" = super.buildPythonPackage rec {
    pname = "alembic";
    version = "1.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/9f/b281de89dde4e26111bbc7d852322a79040eef42692d8772cb46f58303a6/alembic-1.5.5-py2.py3-none-any.whl";
      sha256 = "126pr1azxr2vy6a70v53dwg3l8knk68rhxhjxvbz5g27rj3l1dk5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."Mako"
      self."python-dateutil"
      self."python-editor"
      self."sqlalchemy"
    ];
  };
  "codechecker" = super.buildPythonPackage rec {
    pname = "codechecker";
    version = "6.19.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/e7/f2e943488d799a7f7daaba4811996a096f18e0e0287ca70f55b4beca0f61/codechecker-6.19.1.tar.gz";
      sha256 = "0x3i8b93z0ss34qhvjzjbs3ys2qh6fnbmlgbxbb801kgbqdzxxqd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."PyYAML"
      self."alembic"
      self."gitpython"
      self."lxml"
      self."mypy-extensions"
      self."portalocker"
      self."psutil"
      self."sqlalchemy"
      self."thrift"
    ];
  };
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/7c/5d747655049bfbf75b5fcec57c8115896cb78d6fafa84f6d3ef4c0f13a98/gitdb-4.0.9-py3-none-any.whl";
      sha256 = "1zd8y65kz9hjshj96zmzr27inc495zgvjl10m5nblrihhm7ascw0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "3.1.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/24/d1/a7f8fe3df258549b303415157328bfcc63e9b11d06a7ad7a3327f3d32606/GitPython-3.1.11-py3-none-any.whl";
      sha256 = "0svlkgpr5mmb59vg23cs480czgga2958wrp96w250ywianv8kskf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."gitdb"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/74/4a97db45381316cd6e7d4b1eb707d7f60d38cb2985b5dfd7251a340404da/lxml-4.7.1.tar.gz";
      sha256 = "090viyanaki4q7w7i000xl0qh4in52bkl3qal55sz2bbm8w3hqd1";
    };
    format = "setuptools";
    doCheck = false;
    checkInputs = [ ];
    buildInputs = [
      pkgs.libxml2
      pkgs.libxslt
      pkgs.zlib
    ];
    nativeBuildInputs = [ pkgs.libxml2.dev pkgs.libxslt.dev ];
    propagatedBuildInputs = [ ];
  };
  "mypy-extensions" = super.buildPythonPackage rec {
    pname = "mypy-extensions";
    version = "0.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl";
      sha256 = "0pgi8sl514i9iamzdli8l3sxla7l4ic3nc713klrm9j5b7bys3q9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "portalocker" = super.buildPythonPackage rec {
    pname = "portalocker";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/82/22/e684c9e2e59b561dbe36538852e81849122c666c423448e3a5c99362c228/portalocker-2.2.1-py2.py3-none-any.whl";
      sha256 = "0in13i7wmy0zqf85q57pvir68h62dkr4zdxc68asqyqx0j2nr9mg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "5.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz";
      sha256 = "1immnj532bnnrh1qmk5q3lsw3san8qfk9kxy1cpmy0knmfcwp70c";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl";
      sha256 = "1aaxjfp4lrz8c6qls3vdhw554lan3khy9afyvdcvrssk6kf067cn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-editor" = super.buildPythonPackage rec {
    pname = "python-editor";
    version = "1.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl";
      sha256 = "0z9nr2npc0ghk0jh436qirhk082vq9fjs9g17r6a2lmdm1hfixhv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/01/7caa71608bc29952ae09b0be63a539e50d2484bc37747797a66a60679856/smmap-5.0.0-py3-none-any.whl";
      sha256 = "150d3676rvpfb44wwmcf3pbrxc07cblmfp6y165qvrs0l3b1kfia";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "sqlalchemy" = super.buildPythonPackage rec {
    pname = "sqlalchemy";
    version = "1.3.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/cd/f871773f1c1eb043f639b6751d6342539a45da0836bfede6a6889cea5255/SQLAlchemy-1.3.23.tar.gz";
      sha256 = "12wi4vxjsx4ra76phks9drhc2yc9xz25458kgijnyrkq4mkk7jkg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "thrift" = super.buildPythonPackage rec {
    pname = "thrift";
    version = "0.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/1e/3284d19d7be99305eda145b8aa46b0c33244e4a496ec66440dac19f8274d/thrift-0.13.0.tar.gz";
      sha256 = "12bxmslp0234by4n23fck50bb8mcqsk7dlqf073aycrlyxmwiwcs";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."six"
    ];
  };
}
