# This file has been generated by node2nix 1.8.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:
let
  sources = {
    "@babel/code-frame-7.12.13" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.12.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.12.13.tgz";
        sha512 = "HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupbfx2aXarXuw5Ko5aMcjtJgbSs4vUGBS5v6g==";
      };
    };
    "@babel/helper-validator-identifier-7.12.11" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.12.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.12.11.tgz";
        sha512 = "np/lG3uARFybkoHokJUmf1QfEvRVCPbmQeUQpKow5cQ3xWrV9i3rUHodKDJPQfTVX61qKi+UdYk8kik84n7XOw==";
      };
    };
    "@babel/highlight-7.13.10" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.13.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.13.10.tgz";
        sha512 = "5aPpe5XQPzflQrFwL1/QoeHkP2MsA4JCntcXHRhEsdsfPVkvPi2w7Qix4iV7t5S/oC9OodGrggd8aco1g3SZFg==";
      };
    };
    "@types/mdast-3.0.3" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-3.0.3.tgz";
        sha512 = "SXPBMnFVQg1s00dlMCc/jCdvPqdE4mXaMMCeRlxLDmTAEoegHT53xKtkDnzDTOcmMHUfcjyf36/YYZ6SxRdnsw==";
      };
    };
    "@types/unist-2.0.3" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.3.tgz";
        sha512 = "FvUupuM3rlRsRtCN+fDudtmytGO6iHJuuRKS1Ss0pG5z8oX0diNEw94UEL7hgDbpN94rgaK5R7sWm6RrSkZuAQ==";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "anymatch-3.1.1" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.1.tgz";
        sha512 = "mM8522psRCqzV+6LhomX5wgp25YVibjh8Wj23I5RPkPppSVSjyKD2A2mBJmWGa+KN7f2D6LNh9jkBCeyLktzjg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "bail-1.0.5" = {
      name = "bail";
      packageName = "bail";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bail/-/bail-1.0.5.tgz";
        sha512 = "xFbRxM1tahm08yHBP16MMjVUAvDaBMD38zsM9EMAUN61omwLmKlOpB/Zku5QkjZ8TZ4vn53pj+t518cH0S03RQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "binary-extensions-2.2.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.2.0.tgz";
        sha512 = "jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "camelcase-5.3.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz";
        sha512 = "L28STB170nwWS63UjtlEOE3dldQApaJXZkOI1uMFfzf3rRuPegHaHesyee+YxQ+W6SvRDQV6UrdOdRiR153wJg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-3.0.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-3.0.0.tgz";
        sha512 = "4D3B6Wf41KOYRFdszmDqMCGq5VV/uMAB273JILmO+3jAlh8X4qDtdtgCR3fxtbLEMzSx22QdhnDcJvu2u1fVwg==";
      };
    };
    "character-entities-1.2.4" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-1.2.4.tgz";
        sha512 = "iBMyeEHxfVnIakwOuDXpVkc54HijNgCyQB2w0VfGQThle6NXn50zU6V/u+LDhxHcDUPojn6Kpga3PTAD8W1bQw==";
      };
    };
    "character-entities-legacy-1.1.4" = {
      name = "character-entities-legacy";
      packageName = "character-entities-legacy";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-1.1.4.tgz";
        sha512 = "3Xnr+7ZFS1uxeiUDvV02wQ+QDbc55o97tIV5zHScSPJpcLm/r0DFPcoY3tYRp+VZukxuMeKgXYmsXQHO05zQeA==";
      };
    };
    "character-reference-invalid-1.1.4" = {
      name = "character-reference-invalid";
      packageName = "character-reference-invalid";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-1.1.4.tgz";
        sha512 = "mKKUkUbhPpQlCOfIuZkvSEgktjPFIsZKRRbC6KWVEMvlzblj3i3asQv5ODsrwt0N3pHAEvjP8KTQPHkp0+6jOg==";
      };
    };
    "chokidar-3.5.1" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.5.1.tgz";
        sha512 = "9+s+Od+W0VJJzawDma/gvBNQqkTiqYTWLuZoyAsivsI4AaWTCzHG06/TMjsf1cYe9Cb97UCEhjz7HvnPk2p/tw==";
      };
    };
    "co-3.1.0" = {
      name = "co";
      packageName = "co";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-3.1.0.tgz";
        sha1 = "4ea54ea5a08938153185e15210c68d9092bc1b78";
      };
    };
    "collapse-white-space-1.0.6" = {
      name = "collapse-white-space";
      packageName = "collapse-white-space";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/collapse-white-space/-/collapse-white-space-1.0.6.tgz";
        sha512 = "jEovNnrhMuqyCcjfEJA56v0Xq8SkIoPKDyaHahwo3POf4qcSXqMYuwNcOTzp74vTsR9Tn08z4MxWqAhcekogkQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-2.0.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-2.0.0.tgz";
        sha512 = "MWufYdFw53ccGjCA+Ol7XJYpAlW6/prSMzuPOTRnJGcGzuhLn4Scrz7qf6o8bROZ514ltazcIFJZevcfbo0x7A==";
      };
    };
    "debug-4.3.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.1.tgz";
        sha512 = "doEwdvm4PCeK4K3RQN2ZC2BYUBaxwLARCqZmMjtF8a51J2Rb0xpVloFRnCODwqjpwnAoao4pelN8l3RJdv3gRQ==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fault-1.0.4" = {
      name = "fault";
      packageName = "fault";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fault/-/fault-1.0.4.tgz";
        sha512 = "CJ0HCB5tL5fYTEA7ToAq5+kTwd++Borf1/bifxd9iT70QcXr4MRrO3Llf8Ifs70q+SJcGHFtnIE/Nw6giCtECA==";
      };
    };
    "figgy-pudding-3.5.2" = {
      name = "figgy-pudding";
      packageName = "figgy-pudding";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/figgy-pudding/-/figgy-pudding-3.5.2.tgz";
        sha512 = "0btnI/H8f2pavGMN8w40mlSKOfTK2SVJmBfBeVIj3kNw0swwgzyRq0d5TJVOwodFmtvpPeWPN/MCcfuWF0Ezbw==";
      };
    };
    "figures-3.2.0" = {
      name = "figures";
      packageName = "figures";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-3.2.0.tgz";
        sha512 = "yaduQFRKLXYOGgEn6AZau90j3ggSOyiqXU0F9JZfeXYhNa+Jk4X+s45A2zg5jns87GAFa34BBm2kXw4XpNcbdg==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "find-up-3.0.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-3.0.0.tgz";
        sha512 = "1yD6RmLI1XBfxugvORwlck6f75tYL+iR0jqwsOrOxMZyGYqUuDhJ0l4AXdO1iX/FTs9cBAMEk1gWSEx1kSbylg==";
      };
    };
    "format-0.2.2" = {
      name = "format";
      packageName = "format";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/format/-/format-0.2.2.tgz";
        sha1 = "d6170107e9efdc4ed30c9dc39016df942b5cb58b";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "ignore-5.1.8" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.1.8.tgz";
        sha512 = "BMpfD7PpiETpBl/A6S498BaIJ6Y/ABT93ETbby2fP00v4EbvPBXWEoaR1UBPKs3iR53pJY7EtZk5KACI57i1Uw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "is-alphabetical-1.0.4" = {
      name = "is-alphabetical";
      packageName = "is-alphabetical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-1.0.4.tgz";
        sha512 = "DwzsA04LQ10FHTZuL0/grVDk4rFoVH1pjAToYwBrHSxcrBIGQuXrQMtD5U1b0U2XVgKZCTLLP8u2Qxqhy3l2Vg==";
      };
    };
    "is-alphanumerical-1.0.4" = {
      name = "is-alphanumerical";
      packageName = "is-alphanumerical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-1.0.4.tgz";
        sha512 = "UzoZUr+XfVz3t3v4KyGEniVL9BDRoQtY7tOyrRybkVNjDFWyo1yhXNGrrBTQxp3ib9BLAWs7k2YKBQsFRkZG9A==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-decimal-1.0.4" = {
      name = "is-decimal";
      packageName = "is-decimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-decimal/-/is-decimal-1.0.4.tgz";
        sha512 = "RGdriMmQQvZ2aqaQq3awNA6dCGtKpiDFcOzrTWrDAT2MiWrKQVPmxLGHl7Y2nNu6led0kEyoX0enY0qXYsv9zw==";
      };
    };
    "is-empty-1.2.0" = {
      name = "is-empty";
      packageName = "is-empty";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-empty/-/is-empty-1.2.0.tgz";
        sha1 = "de9bb5b278738a05a0b09a57e1fb4d4a341a9f6b";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.1.tgz";
        sha512 = "5G0tKtBTFImOqDnLB2hG6Bp2qcKEFduo4tZu9MT/H6NQv/ghhy30o55ufafxJ/LdH79LLs2Kfrn85TLKyA7BUg==";
      };
    };
    "is-hexadecimal-1.0.4" = {
      name = "is-hexadecimal";
      packageName = "is-hexadecimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-1.0.4.tgz";
        sha512 = "gyPJuv83bHMpocVYoqof5VDiZveEoGoFL8m3BXNb2VW8Xs+rz9kqO8LOQ5DH6EsuvilT1ApazU0pyl+ytbPtlw==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-obj-2.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz";
        sha512 = "YWnfyRwxL/+SsrWYfOpUtz5b3YD+nyfkHvjbcanzk8zgyO4ASD67uVMRt8k5bM4lLMDnXfriRhOpemw+NfT1eA==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "json-parse-even-better-errors-2.3.1" = {
      name = "json-parse-even-better-errors";
      packageName = "json-parse-even-better-errors";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
        sha512 = "xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "libnpmconfig-1.2.1" = {
      name = "libnpmconfig";
      packageName = "libnpmconfig";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/libnpmconfig/-/libnpmconfig-1.2.1.tgz";
        sha512 = "9esX8rTQAHqarx6qeZqmGQKBNZR5OIbl/Ayr0qQDy3oXja2iFVQQI81R6GZ2a02bSNZ9p3YOGX1O6HHCb1X7kA==";
      };
    };
    "lines-and-columns-1.1.6" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz";
        sha1 = "1c00c743b433cd0a4e80758f7b64a57440d9ff00";
      };
    };
    "load-plugin-3.0.0" = {
      name = "load-plugin";
      packageName = "load-plugin";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-plugin/-/load-plugin-3.0.0.tgz";
        sha512 = "od7eKCCZ62ITvFf8nHHrIiYmgOHb4xVNDRDqxBWSaao5FZyyZVX8OmRCbwjDGPrSrgIulwPNyBsWCGnhiDC0oQ==";
      };
    };
    "locate-path-3.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-3.0.0.tgz";
        sha512 = "7AO748wWnIhNqAuaty2ZWHkQHRSNfPVIsPIfwEOWO22AmaoVrWavlOcMR5nzTLNYvp36X220/maaRsrec1G65A==";
      };
    };
    "longest-streak-2.0.4" = {
      name = "longest-streak";
      packageName = "longest-streak";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest-streak/-/longest-streak-2.0.4.tgz";
        sha512 = "vM6rUVCVUJJt33bnmHiZEvr7wPT78ztX7rojL+LW51bHtLh6HTjx84LA5W4+oa6aKEJA7jJu5LR6vQRBpA5DVg==";
      };
    };
    "markdown-extensions-1.1.1" = {
      name = "markdown-extensions";
      packageName = "markdown-extensions";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-extensions/-/markdown-extensions-1.1.1.tgz";
        sha512 = "WWC0ZuMzCyDHYCasEGs4IPvLyTGftYwh6wIEOULOF0HXcqZlhwRzrK0w2VUlxWA98xnvb/jszw4ZSkJ6ADpM6Q==";
      };
    };
    "mdast-comment-marker-1.1.2" = {
      name = "mdast-comment-marker";
      packageName = "mdast-comment-marker";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-comment-marker/-/mdast-comment-marker-1.1.2.tgz";
        sha512 = "vTFXtmbbF3rgnTh3Zl3irso4LtvwUq/jaDvT2D1JqTGAwaipcS7RpTxzi6KjoRqI9n2yuAhzLDAC8xVTF3XYVQ==";
      };
    };
    "mdast-util-from-markdown-0.8.5" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-0.8.5.tgz";
        sha512 = "2hkTXtYYnr+NubD/g6KGBS/0mFmBcifAsI0yIWRiRo0PjVs6SSOSOdtzbp6kSGnShDN6G5aWZpKQ2lWRy27mWQ==";
      };
    };
    "mdast-util-heading-style-1.0.6" = {
      name = "mdast-util-heading-style";
      packageName = "mdast-util-heading-style";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-heading-style/-/mdast-util-heading-style-1.0.6.tgz";
        sha512 = "8ZuuegRqS0KESgjAGW8zTx4tJ3VNIiIaGFNEzFpRSAQBavVc7AvOo9I4g3crcZBfYisHs4seYh0rAVimO6HyOw==";
      };
    };
    "mdast-util-to-markdown-0.6.5" = {
      name = "mdast-util-to-markdown";
      packageName = "mdast-util-to-markdown";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-markdown/-/mdast-util-to-markdown-0.6.5.tgz";
        sha512 = "XeV9sDE7ZlOQvs45C9UKMtfTcctcaj/pGwH8YLbMHoMOXNNCn2LsqVQOqrF1+/NU8lKDAqozme9SCXWyo9oAcQ==";
      };
    };
    "mdast-util-to-string-1.1.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-1.1.0.tgz";
        sha512 = "jVU0Nr2B9X3MU4tSK7JP1CMkSvOj7X5l/GboG1tKRw52lLF1x2Ju92Ms9tNetCcbfX3hzlM73zYo2NKkWSfF/A==";
      };
    };
    "mdast-util-to-string-2.0.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-2.0.0.tgz";
        sha512 = "AW4DRS3QbBayY/jJmD8437V1Gombjf8RSOUCMFBuo5iHi58AGEgVCKQ+ezHkZZDpAQS75hcBMpLqjpJTjtUL7w==";
      };
    };
    "micromark-2.11.4" = {
      name = "micromark";
      packageName = "micromark";
      version = "2.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-2.11.4.tgz";
        sha512 = "+WoovN/ppKolQOFIAajxi7Lu9kInbPxFuTBVEavFcL8eAfVstoc5MocPmqBeAdBOJV00uaVjegzH4+MA0DN/uA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "p-limit-2.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
        sha512 = "//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      };
    };
    "p-locate-3.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-3.0.0.tgz";
        sha512 = "x+12w/To+4GFfgJhBEpiDcLozRJGegY+Ei7/z0tSLkMmxGZNybVMSfWj9aJn8Z5Fc7dBUNJOOVgPv2H7IwulSQ==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "parse-entities-2.0.0" = {
      name = "parse-entities";
      packageName = "parse-entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-entities/-/parse-entities-2.0.0.tgz";
        sha512 = "kkywGpCcRYhqQIchaWqZ875wzpS/bMKhz5HnN3p7wveJTkTtyAB/AlnS0f8DFSqYW1T82t6yEAkEcB+A1I3MbQ==";
      };
    };
    "parse-json-5.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-5.2.0.tgz";
        sha512 = "ayCKvm/phCGxOkYRSCM82iDwct8/EonSEgCSxWxD7ve6jHggsFl4fZVQBPRNgQoKiuV/odhFrGzQXZwbifC8Rg==";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "picomatch-2.2.2" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.2.2.tgz";
        sha512 = "q0M/9eZHzmr0AulXyPwNfZjtwZ/RBZlbN3K3CErVrk50T2ASYI7Bye0EvekFY3IP1Nt2DHu0re+V2ZHIpMkuWg==";
      };
    };
    "pluralize-8.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-8.0.0.tgz";
        sha512 = "Nc3IT5yHzflTfbjgqWcCPpo7DaKy4FnpB0l/zCAW0Tc7jxAiuqSxHasntB3D7887LSrA93kDJ9IXovxJYxyLCA==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "readdirp-3.5.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.5.0.tgz";
        sha512 = "cMhu7c/8rdhkHXWsY+osBhfSy0JikwpHK/5+imo+LpeasTF8ouErHrlYkwT0++njiyuDvc7OFY5T3ukvZ8qmFQ==";
      };
    };
    "remark-13.0.0" = {
      name = "remark";
      packageName = "remark";
      version = "13.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark/-/remark-13.0.0.tgz";
        sha512 = "HDz1+IKGtOyWN+QgBiAT0kn+2s6ovOxHyPAFGKVE81VSzJ+mq7RwHFledEvB5F1p4iJvOah/LOKdFuzvRnNLCA==";
      };
    };
    "remark-cli-9.0.0" = {
      name = "remark-cli";
      packageName = "remark-cli";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-cli/-/remark-cli-9.0.0.tgz";
        sha512 = "y6kCXdwZoMoh0Wo4Och1tDW50PmMc86gW6GpF08v9d+xUCEJE2wwXdQ+TnTaUamRnfFdU+fE+eNf2PJ53cyq8g==";
      };
    };
    "remark-lint-8.0.0" = {
      name = "remark-lint";
      packageName = "remark-lint";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint/-/remark-lint-8.0.0.tgz";
        sha512 = "ESI8qJQ/TIRjABDnqoFsTiZntu+FRifZ5fJ77yX63eIDijl/arvmDvT+tAf75/Nm5BFL4R2JFUtkHRGVjzYUsg==";
      };
    };
    "remark-lint-blockquote-indentation-2.0.1" = {
      name = "remark-lint-blockquote-indentation";
      packageName = "remark-lint-blockquote-indentation";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-blockquote-indentation/-/remark-lint-blockquote-indentation-2.0.1.tgz";
        sha512 = "uJ9az/Ms9AapnkWpLSCJfawBfnBI2Tn1yUsPNqIFv6YM98ymetItUMyP6ng9NFPqDvTQBbiarulkgoEo0wcafQ==";
      };
    };
    "remark-lint-checkbox-character-style-3.0.0" = {
      name = "remark-lint-checkbox-character-style";
      packageName = "remark-lint-checkbox-character-style";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-checkbox-character-style/-/remark-lint-checkbox-character-style-3.0.0.tgz";
        sha512 = "691OJ5RdBRXVpvnOEiBhMB4uhHJSHVttw83O4qyAkNBiqxa1Axqhsz8FgmzYgRLQbOGd2ncVUcXG1LOJt6C0DQ==";
      };
    };
    "remark-lint-code-block-style-2.0.1" = {
      name = "remark-lint-code-block-style";
      packageName = "remark-lint-code-block-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-code-block-style/-/remark-lint-code-block-style-2.0.1.tgz";
        sha512 = "eRhmnColmSxJhO61GHZkvO67SpHDshVxs2j3+Zoc5Y1a4zQT2133ZAij04XKaBFfsVLjhbY/+YOWxgvtjx2nmA==";
      };
    };
    "remark-lint-definition-case-2.0.1" = {
      name = "remark-lint-definition-case";
      packageName = "remark-lint-definition-case";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-definition-case/-/remark-lint-definition-case-2.0.1.tgz";
        sha512 = "M+XlThtQwEJLQnQb5Gi6xZdkw92rGp7m2ux58WMw/Qlcg02WgHR/O0OcHPe5VO5hMJrtI+cGG5T0svsCgRZd3w==";
      };
    };
    "remark-lint-definition-spacing-2.0.1" = {
      name = "remark-lint-definition-spacing";
      packageName = "remark-lint-definition-spacing";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-definition-spacing/-/remark-lint-definition-spacing-2.0.1.tgz";
        sha512 = "xK9DOQO5MudITD189VyUiMHBIKltW1oc55L7Fti3i9DedXoBG7Phm+V9Mm7IdWzCVkquZVgVk63xQdqzSQRrSQ==";
      };
    };
    "remark-lint-emphasis-marker-2.0.1" = {
      name = "remark-lint-emphasis-marker";
      packageName = "remark-lint-emphasis-marker";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-emphasis-marker/-/remark-lint-emphasis-marker-2.0.1.tgz";
        sha512 = "7mpbAUrSnHiWRyGkbXRL5kfSKY9Cs8cdob7Fw+Z02/pufXMF4yRWaegJ5NTUu1RE+SKlF44wtWWjvcIoyY6/aw==";
      };
    };
    "remark-lint-fenced-code-flag-2.0.1" = {
      name = "remark-lint-fenced-code-flag";
      packageName = "remark-lint-fenced-code-flag";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-fenced-code-flag/-/remark-lint-fenced-code-flag-2.0.1.tgz";
        sha512 = "+COnWHlS/h02FMxoZWxNlZW3Y8M0cQQpmx3aNCbG7xkyMyCKsMLg9EmRvYHHIbxQCuF3JT0WWx5AySqlc7d+NA==";
      };
    };
    "remark-lint-fenced-code-marker-2.0.1" = {
      name = "remark-lint-fenced-code-marker";
      packageName = "remark-lint-fenced-code-marker";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-fenced-code-marker/-/remark-lint-fenced-code-marker-2.0.1.tgz";
        sha512 = "lujpjm04enn3ma6lITlttadld6eQ1OWAEcT3qZzvFHp+zPraC0yr0eXlvtDN/0UH8mrln/QmGiZp3i8IdbucZg==";
      };
    };
    "remark-lint-file-extension-1.0.5" = {
      name = "remark-lint-file-extension";
      packageName = "remark-lint-file-extension";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-file-extension/-/remark-lint-file-extension-1.0.5.tgz";
        sha512 = "oVQdf5vEomwHkfQ7R/mgmsWW2H/t9kSvnrxtVoNOHr+qnOEafKKDn+AFhioN2kqtjCZBAjSSrePs6xGKmXKDTw==";
      };
    };
    "remark-lint-final-definition-2.1.0" = {
      name = "remark-lint-final-definition";
      packageName = "remark-lint-final-definition";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-final-definition/-/remark-lint-final-definition-2.1.0.tgz";
        sha512 = "83K7n2icOHPfBzbR5Mr1o7cu8gOjD8FwJkFx/ly+rW+8SHfjCj4D3WOFGQ1xVdmHjfomBDXXDSNo2oiacADVXQ==";
      };
    };
    "remark-lint-final-newline-1.0.5" = {
      name = "remark-lint-final-newline";
      packageName = "remark-lint-final-newline";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-final-newline/-/remark-lint-final-newline-1.0.5.tgz";
        sha512 = "rfLlW8+Fz2dqnaEgU4JwLA55CQF1T4mfSs/GwkkeUCGPenvEYwSkCN2KO2Gr1dy8qPoOdTFE1rSufLjmeTW5HA==";
      };
    };
    "remark-lint-hard-break-spaces-2.0.1" = {
      name = "remark-lint-hard-break-spaces";
      packageName = "remark-lint-hard-break-spaces";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-hard-break-spaces/-/remark-lint-hard-break-spaces-2.0.1.tgz";
        sha512 = "Qfn/BMQFamHhtbfLrL8Co/dbYJFLRL4PGVXZ5wumkUO5f9FkZC2RsV+MD9lisvGTkJK0ZEJrVVeaPbUIFM0OAw==";
      };
    };
    "remark-lint-heading-increment-2.0.1" = {
      name = "remark-lint-heading-increment";
      packageName = "remark-lint-heading-increment";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-heading-increment/-/remark-lint-heading-increment-2.0.1.tgz";
        sha512 = "bYDRmv/lk3nuWXs2VSD1B4FneGT6v7a74FuVmb305hyEMmFSnneJvVgnOJxyKlbNlz12pq1IQ6MhlJBda/SFtQ==";
      };
    };
    "remark-lint-heading-style-2.0.1" = {
      name = "remark-lint-heading-style";
      packageName = "remark-lint-heading-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-heading-style/-/remark-lint-heading-style-2.0.1.tgz";
        sha512 = "IrFLNs0M5Vbn9qg51AYhGUfzgLAcDOjh2hFGMz3mx664dV6zLcNZOPSdJBBJq3JQR4gKpoXcNwN1+FFaIATj+A==";
      };
    };
    "remark-lint-link-title-style-2.0.1" = {
      name = "remark-lint-link-title-style";
      packageName = "remark-lint-link-title-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-link-title-style/-/remark-lint-link-title-style-2.0.1.tgz";
        sha512 = "+Q7Ew8qpOQzjqbDF6sUHmn9mKgje+m2Ho8Xz7cEnGIRaKJgtJzkn/dZqQM/az0gn3zaN6rOuwTwqw4EsT5EsIg==";
      };
    };
    "remark-lint-list-item-bullet-indent-3.0.0" = {
      name = "remark-lint-list-item-bullet-indent";
      packageName = "remark-lint-list-item-bullet-indent";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-bullet-indent/-/remark-lint-list-item-bullet-indent-3.0.0.tgz";
        sha512 = "X2rleWP8XReC4LXKF7Qi5vYiPJkA4Grx5zxsjHofFrVRz6j0PYOCuz7vsO+ZzMunFMfom6FODnscSWz4zouDVw==";
      };
    };
    "remark-lint-list-item-content-indent-2.0.1" = {
      name = "remark-lint-list-item-content-indent";
      packageName = "remark-lint-list-item-content-indent";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-content-indent/-/remark-lint-list-item-content-indent-2.0.1.tgz";
        sha512 = "OzUMqavxyptAdG7vWvBSMc9mLW9ZlTjbW4XGayzczd3KIr6Uwp3NEFXKx6MLtYIM/vwBqMrPQUrObOC7A2uBpQ==";
      };
    };
    "remark-lint-list-item-indent-2.0.1" = {
      name = "remark-lint-list-item-indent";
      packageName = "remark-lint-list-item-indent";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-indent/-/remark-lint-list-item-indent-2.0.1.tgz";
        sha512 = "4IKbA9GA14Q9PzKSQI6KEHU/UGO36CSQEjaDIhmb9UOhyhuzz4vWhnSIsxyI73n9nl9GGRAMNUSGzr4pQUFwTA==";
      };
    };
    "remark-lint-list-item-spacing-3.0.0" = {
      name = "remark-lint-list-item-spacing";
      packageName = "remark-lint-list-item-spacing";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-spacing/-/remark-lint-list-item-spacing-3.0.0.tgz";
        sha512 = "SRUVonwdN3GOSFb6oIYs4IfJxIVR+rD0nynkX66qEO49/qDDT1PPvkndis6Nyew5+t+2V/Db9vqllL6SWbnEtw==";
      };
    };
    "remark-lint-maximum-heading-length-2.0.1" = {
      name = "remark-lint-maximum-heading-length";
      packageName = "remark-lint-maximum-heading-length";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-maximum-heading-length/-/remark-lint-maximum-heading-length-2.0.1.tgz";
        sha512 = "1CjJ71YDqEpoOjUnc4wrwZV8ZGXWUIYRYeGoarAy3QKHepJL9M+zkdbOxZDfhc3tjVoDW/LWcgsW+DEpczgiMA==";
      };
    };
    "remark-lint-maximum-line-length-2.0.3" = {
      name = "remark-lint-maximum-line-length";
      packageName = "remark-lint-maximum-line-length";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-maximum-line-length/-/remark-lint-maximum-line-length-2.0.3.tgz";
        sha512 = "zyWHBFh1oPAy+gkaVFXiTHYP2WwriIeBtaarDqkweytw0+qmuikjVMJTWbQ3+XfYBreD7KKDM9SI79nkp0/IZQ==";
      };
    };
    "remark-lint-no-auto-link-without-protocol-2.0.1" = {
      name = "remark-lint-no-auto-link-without-protocol";
      packageName = "remark-lint-no-auto-link-without-protocol";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-auto-link-without-protocol/-/remark-lint-no-auto-link-without-protocol-2.0.1.tgz";
        sha512 = "TFcXxzucsfBb/5uMqGF1rQA+WJJqm1ZlYQXyvJEXigEZ8EAxsxZGPb/gOQARHl/y0vymAuYxMTaChavPKaBqpQ==";
      };
    };
    "remark-lint-no-blockquote-without-marker-4.0.0" = {
      name = "remark-lint-no-blockquote-without-marker";
      packageName = "remark-lint-no-blockquote-without-marker";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-blockquote-without-marker/-/remark-lint-no-blockquote-without-marker-4.0.0.tgz";
        sha512 = "Y59fMqdygRVFLk1gpx2Qhhaw5IKOR9T38Wf7pjR07bEFBGUNfcoNVIFMd1TCJfCPQxUyJzzSqfZz/KT7KdUuiQ==";
      };
    };
    "remark-lint-no-consecutive-blank-lines-3.0.0" = {
      name = "remark-lint-no-consecutive-blank-lines";
      packageName = "remark-lint-no-consecutive-blank-lines";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-consecutive-blank-lines/-/remark-lint-no-consecutive-blank-lines-3.0.0.tgz";
        sha512 = "kmzLlOLrapBKEngwYFTdCZDmeOaze6adFPB7G0EdymD9V1mpAlnneINuOshRLEDKK5fAhXKiZXxdGIaMPkiXrA==";
      };
    };
    "remark-lint-no-duplicate-definitions-2.0.1" = {
      name = "remark-lint-no-duplicate-definitions";
      packageName = "remark-lint-no-duplicate-definitions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-duplicate-definitions/-/remark-lint-no-duplicate-definitions-2.0.1.tgz";
        sha512 = "XL22benJZB01m+aOse91nsu1IMFqeWJWme9QvoJuxIcBROO1BG1VoqLOkwNcawE/M/0CkvTo5rfx0eMlcnXOIw==";
      };
    };
    "remark-lint-no-duplicate-headings-2.0.1" = {
      name = "remark-lint-no-duplicate-headings";
      packageName = "remark-lint-no-duplicate-headings";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-duplicate-headings/-/remark-lint-no-duplicate-headings-2.0.1.tgz";
        sha512 = "F6AP0FJcHIlkmq0pHX0J5EGvLA9LfhuYTvnNO8y3kvflHeRjFkDyt2foz/taXR8OcLQR51n/jIJiwrrSMbiauw==";
      };
    };
    "remark-lint-no-emphasis-as-heading-2.0.1" = {
      name = "remark-lint-no-emphasis-as-heading";
      packageName = "remark-lint-no-emphasis-as-heading";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-emphasis-as-heading/-/remark-lint-no-emphasis-as-heading-2.0.1.tgz";
        sha512 = "z86+yWtVivtuGIxIC4g9RuATbgZgOgyLcnaleonJ7/HdGTYssjJNyqCJweaWSLoaI0akBQdDwmtJahW5iuX3/g==";
      };
    };
    "remark-lint-no-file-name-articles-1.0.5" = {
      name = "remark-lint-no-file-name-articles";
      packageName = "remark-lint-no-file-name-articles";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-articles/-/remark-lint-no-file-name-articles-1.0.5.tgz";
        sha512 = "AQk5eTb3s3TAPPjiglZgqlQj4ycao+gPs8/XkdN1VCPUtewW0GgwoQe7YEuBKayJ6ioN8dGP37Kg/P/PlKaRQA==";
      };
    };
    "remark-lint-no-file-name-consecutive-dashes-1.0.5" = {
      name = "remark-lint-no-file-name-consecutive-dashes";
      packageName = "remark-lint-no-file-name-consecutive-dashes";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-consecutive-dashes/-/remark-lint-no-file-name-consecutive-dashes-1.0.5.tgz";
        sha512 = "Mg2IDsi790/dSdAzwnBnsMYdZm3qC2QgGwqOWcr0TPABJhhjC3p8r5fX4MNMTXI5It7B7bW9+ImmCeLOZiXkLg==";
      };
    };
    "remark-lint-no-file-name-irregular-characters-1.0.5" = {
      name = "remark-lint-no-file-name-irregular-characters";
      packageName = "remark-lint-no-file-name-irregular-characters";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-irregular-characters/-/remark-lint-no-file-name-irregular-characters-1.0.5.tgz";
        sha512 = "Oe5i99qNUKc2bxmiH421o5B/kqlf1dfjAxpHNLhi2X2dXE91zRGavrlRM/4f4oR0N9Bqb3qB9JZPyMPWrzu9XA==";
      };
    };
    "remark-lint-no-file-name-mixed-case-1.0.5" = {
      name = "remark-lint-no-file-name-mixed-case";
      packageName = "remark-lint-no-file-name-mixed-case";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-mixed-case/-/remark-lint-no-file-name-mixed-case-1.0.5.tgz";
        sha512 = "ilrUCbHZin/ENwr8c3SC2chgkFsizXjBQIB/oZ7gnm1IkCkZPiMyXZAHdpwC/DjbrpGxfMYh9JmIHao4giS5+A==";
      };
    };
    "remark-lint-no-file-name-outer-dashes-1.0.6" = {
      name = "remark-lint-no-file-name-outer-dashes";
      packageName = "remark-lint-no-file-name-outer-dashes";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-outer-dashes/-/remark-lint-no-file-name-outer-dashes-1.0.6.tgz";
        sha512 = "rT8CmcIlenegS0Yst4maYXdZfqIjBOiRUY8j/KJkORF5tKH+3O1/S07025qPGmcRihzK3w4yO0K8rgkKQw0b9w==";
      };
    };
    "remark-lint-no-heading-content-indent-3.0.0" = {
      name = "remark-lint-no-heading-content-indent";
      packageName = "remark-lint-no-heading-content-indent";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-heading-content-indent/-/remark-lint-no-heading-content-indent-3.0.0.tgz";
        sha512 = "yULDoVSIqKylLDfW6mVUbrHlyEWUSFtVFiKc+/BA412xDIhm8HZLUnP+FsuBC0OzbIZ+bO9Txy52WtO3LGnK1A==";
      };
    };
    "remark-lint-no-heading-punctuation-2.0.1" = {
      name = "remark-lint-no-heading-punctuation";
      packageName = "remark-lint-no-heading-punctuation";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-heading-punctuation/-/remark-lint-no-heading-punctuation-2.0.1.tgz";
        sha512 = "lY/eF6GbMeGu4cSuxfGHyvaQQBIq/6T/o+HvAR5UfxSTxmxZFwbZneAI2lbeR1zPcqOU87NsZ5ZZzWVwdLpPBw==";
      };
    };
    "remark-lint-no-inline-padding-3.0.0" = {
      name = "remark-lint-no-inline-padding";
      packageName = "remark-lint-no-inline-padding";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-inline-padding/-/remark-lint-no-inline-padding-3.0.0.tgz";
        sha512 = "3s9uW3Yux9RFC0xV81MQX3bsYs+UY7nPnRuMxeIxgcVwxQ4E/mTJd9QjXUwBhU9kdPtJ5AalngdmOW2Tgar8Cg==";
      };
    };
    "remark-lint-no-literal-urls-2.0.1" = {
      name = "remark-lint-no-literal-urls";
      packageName = "remark-lint-no-literal-urls";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-literal-urls/-/remark-lint-no-literal-urls-2.0.1.tgz";
        sha512 = "IDdKtWOMuKVQIlb1CnsgBoyoTcXU3LppelDFAIZePbRPySVHklTtuK57kacgU5grc7gPM04bZV96eliGrRU7Iw==";
      };
    };
    "remark-lint-no-multiple-toplevel-headings-2.0.1" = {
      name = "remark-lint-no-multiple-toplevel-headings";
      packageName = "remark-lint-no-multiple-toplevel-headings";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-multiple-toplevel-headings/-/remark-lint-no-multiple-toplevel-headings-2.0.1.tgz";
        sha512 = "VKSItR6c+u3OsE5pUiSmNusERNyQS9Nnji26ezoQ1uvy06k3RypIjmzQqJ/hCkSiF+hoyC3ibtrrGT8gorzCmQ==";
      };
    };
    "remark-lint-no-shell-dollars-2.0.2" = {
      name = "remark-lint-no-shell-dollars";
      packageName = "remark-lint-no-shell-dollars";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shell-dollars/-/remark-lint-no-shell-dollars-2.0.2.tgz";
        sha512 = "zhkHZOuyaD3r/TUUkkVqW0OxsR9fnSrAnHIF63nfJoAAUezPOu8D1NBsni6rX8H2DqGbPYkoeWrNsTwiKP0yow==";
      };
    };
    "remark-lint-no-shortcut-reference-image-2.0.1" = {
      name = "remark-lint-no-shortcut-reference-image";
      packageName = "remark-lint-no-shortcut-reference-image";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shortcut-reference-image/-/remark-lint-no-shortcut-reference-image-2.0.1.tgz";
        sha512 = "2jcZBdnN6ecP7u87gkOVFrvICLXIU5OsdWbo160FvS/2v3qqqwF2e/n/e7D9Jd+KTq1mR1gEVVuTqkWWuh3cig==";
      };
    };
    "remark-lint-no-shortcut-reference-link-2.0.1" = {
      name = "remark-lint-no-shortcut-reference-link";
      packageName = "remark-lint-no-shortcut-reference-link";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shortcut-reference-link/-/remark-lint-no-shortcut-reference-link-2.0.1.tgz";
        sha512 = "pTZbslG412rrwwGQkIboA8wpBvcjmGFmvugIA+UQR+GfFysKtJ5OZMPGJ98/9CYWjw9Z5m0/EktplZ5TjFjqwA==";
      };
    };
    "remark-lint-no-table-indentation-3.0.0" = {
      name = "remark-lint-no-table-indentation";
      packageName = "remark-lint-no-table-indentation";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-table-indentation/-/remark-lint-no-table-indentation-3.0.0.tgz";
        sha512 = "+l7GovI6T+3LhnTtz/SmSRyOb6Fxy6tmaObKHrwb/GAebI/4MhFS1LVo3vbiP/RpPYtyQoFbbuXI55hqBG4ibQ==";
      };
    };
    "remark-lint-no-undefined-references-3.0.0" = {
      name = "remark-lint-no-undefined-references";
      packageName = "remark-lint-no-undefined-references";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-undefined-references/-/remark-lint-no-undefined-references-3.0.0.tgz";
        sha512 = "0hzaJS9GuzSQVOeeNdJr/s66LRQOzp618xuOQPYWHcJdd+SCaRTyWbjMrTM/cCI5L1sYjgurp410NkIBQ32Vqg==";
      };
    };
    "remark-lint-no-unused-definitions-2.0.1" = {
      name = "remark-lint-no-unused-definitions";
      packageName = "remark-lint-no-unused-definitions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-unused-definitions/-/remark-lint-no-unused-definitions-2.0.1.tgz";
        sha512 = "+BMc0BOjc364SvKYLkspmxDch8OaKPbnUGgQBvK0Bmlwy42baR4C9zhwAWBxm0SBy5Z4AyM4G4jKpLXPH40Oxg==";
      };
    };
    "remark-lint-ordered-list-marker-style-2.0.1" = {
      name = "remark-lint-ordered-list-marker-style";
      packageName = "remark-lint-ordered-list-marker-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-ordered-list-marker-style/-/remark-lint-ordered-list-marker-style-2.0.1.tgz";
        sha512 = "Cnpw1Dn9CHn+wBjlyf4qhPciiJroFOEGmyfX008sQ8uGoPZsoBVIJx76usnHklojSONbpjEDcJCjnOvfAcWW1A==";
      };
    };
    "remark-lint-ordered-list-marker-value-2.0.1" = {
      name = "remark-lint-ordered-list-marker-value";
      packageName = "remark-lint-ordered-list-marker-value";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-ordered-list-marker-value/-/remark-lint-ordered-list-marker-value-2.0.1.tgz";
        sha512 = "blt9rS7OKxZ2NW8tqojELeyNEwPhhTJGVa+YpUkdEH+KnrdcD7Nzhnj6zfLWOx6jFNZk3jpq5nvLFAPteHaNKg==";
      };
    };
    "remark-lint-rule-style-2.0.1" = {
      name = "remark-lint-rule-style";
      packageName = "remark-lint-rule-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-rule-style/-/remark-lint-rule-style-2.0.1.tgz";
        sha512 = "hz4Ff9UdlYmtO6Czz99WJavCjqCer7Cav4VopXt+yVIikObw96G5bAuLYcVS7hvMUGqC9ZuM02/Y/iq9n8pkAg==";
      };
    };
    "remark-lint-strong-marker-2.0.1" = {
      name = "remark-lint-strong-marker";
      packageName = "remark-lint-strong-marker";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-strong-marker/-/remark-lint-strong-marker-2.0.1.tgz";
        sha512 = "8X2IsW1jZ5FmW9PLfQjkL0OVy/J3xdXLcZrG1GTeQKQ91BrPFyEZqUM2oM6Y4S6LGtxWer+neZkPZNroZoRPBQ==";
      };
    };
    "remark-lint-table-cell-padding-3.0.0" = {
      name = "remark-lint-table-cell-padding";
      packageName = "remark-lint-table-cell-padding";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-cell-padding/-/remark-lint-table-cell-padding-3.0.0.tgz";
        sha512 = "sEKrbyFZPZpxI39R8/r+CwUrin9YtyRwVn0SQkNQEZWZcIpylK+bvoKIldvLIXQPob+ZxklL0GPVRzotQMwuWQ==";
      };
    };
    "remark-lint-table-pipe-alignment-2.0.1" = {
      name = "remark-lint-table-pipe-alignment";
      packageName = "remark-lint-table-pipe-alignment";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-pipe-alignment/-/remark-lint-table-pipe-alignment-2.0.1.tgz";
        sha512 = "O89U7bp0ja6uQkT2uQrNB76GaPvFabrHiUGhqEUnld21yEdyj7rgS57kn84lZNSuuvN1Oor6bDyCwWQGzzpoOQ==";
      };
    };
    "remark-lint-table-pipes-3.0.0" = {
      name = "remark-lint-table-pipes";
      packageName = "remark-lint-table-pipes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-pipes/-/remark-lint-table-pipes-3.0.0.tgz";
        sha512 = "QPokSazEdl0Y8ayUV9UB0Ggn3Jos/RAQwIo0z1KDGnJlGDiF80Jc6iU9RgDNUOjlpQffSLIfSVxH5VVYF/K3uQ==";
      };
    };
    "remark-lint-unordered-list-marker-style-2.0.1" = {
      name = "remark-lint-unordered-list-marker-style";
      packageName = "remark-lint-unordered-list-marker-style";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-unordered-list-marker-style/-/remark-lint-unordered-list-marker-style-2.0.1.tgz";
        sha512 = "8KIDJNDtgbymEvl3LkrXgdxPMTOndcux3BHhNGB2lU4UnxSpYeHsxcDgirbgU6dqCAfQfvMjPvfYk19QTF9WZA==";
      };
    };
    "remark-message-control-6.0.0" = {
      name = "remark-message-control";
      packageName = "remark-message-control";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-message-control/-/remark-message-control-6.0.0.tgz";
        sha512 = "k9bt7BYc3G7YBdmeAhvd3VavrPa/XlKWR3CyHjr4sLO9xJyly8WHHT3Sp+8HPR8lEUv+/sZaffL7IjMLV0f6BA==";
      };
    };
    "remark-parse-9.0.0" = {
      name = "remark-parse";
      packageName = "remark-parse";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-parse/-/remark-parse-9.0.0.tgz";
        sha512 = "geKatMwSzEXKHuzBNU1z676sGcDcFoChMK38TgdHJNAYfFtsfHDQG7MoJAjs6sgYMqyLduCYWDIWZIxiPeafEw==";
      };
    };
    "remark-preset-lint-consistent-4.0.0" = {
      name = "remark-preset-lint-consistent";
      packageName = "remark-preset-lint-consistent";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-preset-lint-consistent/-/remark-preset-lint-consistent-4.0.0.tgz";
        sha512 = "1euNZfRanM3wysHAR0vYX6uMbbKTlmTc+QvrymgRayKV8uhslQBISa+XduWk7mSz68ylS8CRR7JGvBfi6kDQjg==";
      };
    };
    "remark-preset-lint-markdown-style-guide-4.0.0" = {
      name = "remark-preset-lint-markdown-style-guide";
      packageName = "remark-preset-lint-markdown-style-guide";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-preset-lint-markdown-style-guide/-/remark-preset-lint-markdown-style-guide-4.0.0.tgz";
        sha512 = "gczDlfZ28Fz0IN/oddy0AH4CiTu9S8d3pJWUsrnwFiafjhJjPGobGE1OD3bksi53md1Bp4K0fzo99YYfvB4Sjw==";
      };
    };
    "remark-preset-lint-recommended-5.0.0" = {
      name = "remark-preset-lint-recommended";
      packageName = "remark-preset-lint-recommended";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-preset-lint-recommended/-/remark-preset-lint-recommended-5.0.0.tgz";
        sha512 = "uu+Ab8JCwMMaKvvB0LOWTWtM3uAvJbKQM/oyWCEJqj7lUVNTKZS575Ro5rKM3Dx7kQjjR1iw0e99bpAYTc5xNA==";
      };
    };
    "remark-stringify-9.0.1" = {
      name = "remark-stringify";
      packageName = "remark-stringify";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-stringify/-/remark-stringify-9.0.1.tgz";
        sha512 = "mWmNg3ZtESvZS8fv5PTvaPckdL4iNlCHTt8/e/8oN08nArHRHjNZMKzA/YW3+p7/lYqIw4nx1XsjCBo/AxNChg==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sliced-1.0.1" = {
      name = "sliced";
      packageName = "sliced";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sliced/-/sliced-1.0.1.tgz";
        sha1 = "0b3a662b5d04c3177b1926bea82b03f837a2ef41";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "string-width-4.2.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.2.tgz";
        sha512 = "XBJbT3N4JhVumXE0eoLU9DCjcaF92KLNqTmFCnG1pf8duUxFGwtP6AD6nkjw9a3IdiRtL3E2w3JDiE/xi3vOeA==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "to-vfile-6.1.0" = {
      name = "to-vfile";
      packageName = "to-vfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-vfile/-/to-vfile-6.1.0.tgz";
        sha512 = "BxX8EkCxOAZe+D/ToHdDsJcVI4HqQfmw0tCkp31zf3dNP/XWIAjU4CmeuSwsSoOzOTqHPOL0KUzyZqJplkD0Qw==";
      };
    };
    "trough-1.0.5" = {
      name = "trough";
      packageName = "trough";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/trough/-/trough-1.0.5.tgz";
        sha512 = "rvuRbTarPXmMb79SmzEp8aqXNKcK+y0XaB298IXueQ8I2PsrATcPBCSPyK/dDNa2iWOhKlfNnOjdAOTBU/nkFA==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "unified-9.2.1" = {
      name = "unified";
      packageName = "unified";
      version = "9.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified/-/unified-9.2.1.tgz";
        sha512 = "juWjuI8Z4xFg8pJbnEZ41b5xjGUWGHqXALmBZ3FC3WX0PIx1CZBIIJ6mXbYMcf6Yw4Fi0rFUTA1cdz/BglbOhA==";
      };
    };
    "unified-args-8.1.0" = {
      name = "unified-args";
      packageName = "unified-args";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-args/-/unified-args-8.1.0.tgz";
        sha512 = "t1HPS1cQPsVvt/6EtyWIbQGurza5684WGRigNghZRvzIdHm3LPgMdXPyGx0npORKzdiy5+urkF0rF5SXM8lBuQ==";
      };
    };
    "unified-engine-8.1.0" = {
      name = "unified-engine";
      packageName = "unified-engine";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-engine/-/unified-engine-8.1.0.tgz";
        sha512 = "ptXTWUf9HZ2L9xto7tre+hSdSN7M9S0rypUpMAcFhiDYjrXLrND4If+8AZOtPFySKI/Zhfxf7GVAR34BqixDUA==";
      };
    };
    "unified-lint-rule-1.0.6" = {
      name = "unified-lint-rule";
      packageName = "unified-lint-rule";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-lint-rule/-/unified-lint-rule-1.0.6.tgz";
        sha512 = "YPK15YBFwnsVorDFG/u0cVVQN5G2a3V8zv5/N6KN3TCG+ajKtaALcy7u14DCSrJI+gZeyYquFL9cioJXOGXSvg==";
      };
    };
    "unified-message-control-3.0.3" = {
      name = "unified-message-control";
      packageName = "unified-message-control";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-message-control/-/unified-message-control-3.0.3.tgz";
        sha512 = "oY5z2n8ugjpNHXOmcgrw0pQeJzavHS0VjPBP21tOcm7rc2C+5Q+kW9j5+gqtf8vfW/8sabbsK5+P+9QPwwEHDA==";
      };
    };
    "unist-util-generated-1.1.6" = {
      name = "unist-util-generated";
      packageName = "unist-util-generated";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-generated/-/unist-util-generated-1.1.6.tgz";
        sha512 = "cln2Mm1/CZzN5ttGK7vkoGw+RZ8VcUH6BtGbq98DDtRGquAAOXig1mrBQYelOwMXYS8rK+vZDyyojSjp7JX+Lg==";
      };
    };
    "unist-util-inspect-5.0.1" = {
      name = "unist-util-inspect";
      packageName = "unist-util-inspect";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-inspect/-/unist-util-inspect-5.0.1.tgz";
        sha512 = "fPNWewS593JSmg49HbnE86BJKuBi1/nMWhDSccBvbARfxezEuJV85EaARR9/VplveiwCoLm2kWq+DhP8TBaDpw==";
      };
    };
    "unist-util-is-4.1.0" = {
      name = "unist-util-is";
      packageName = "unist-util-is";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-is/-/unist-util-is-4.1.0.tgz";
        sha512 = "ZOQSsnce92GrxSqlnEEseX0gi7GH9zTJZ0p9dtu87WRb/37mMPO2Ilx1s/t9vBHrFhbgweUwb+t7cIn5dxPhZg==";
      };
    };
    "unist-util-position-3.1.0" = {
      name = "unist-util-position";
      packageName = "unist-util-position";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-position/-/unist-util-position-3.1.0.tgz";
        sha512 = "w+PkwCbYSFw8vpgWD0v7zRCl1FpY3fjDSQ3/N/wNd9Ffa4gPi8+4keqt99N3XW6F99t/mUzp2xAhNmfKWp95QA==";
      };
    };
    "unist-util-stringify-position-2.0.3" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-2.0.3.tgz";
        sha512 = "3faScn5I+hy9VleOq/qNbAd6pAx7iH5jYBMS9I1HgQVijz/4mv5Bvw5iw1sC/90CODiKo81G/ps8AJrISn687g==";
      };
    };
    "unist-util-visit-2.0.3" = {
      name = "unist-util-visit";
      packageName = "unist-util-visit";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit/-/unist-util-visit-2.0.3.tgz";
        sha512 = "iJ4/RczbJMkD0712mGktuGpm/U4By4FfDonL7N/9tATGIF4imikjOuagyMY53tnZq3NP6BcmlrHhEKAfGWjh7Q==";
      };
    };
    "unist-util-visit-parents-3.1.1" = {
      name = "unist-util-visit-parents";
      packageName = "unist-util-visit-parents";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit-parents/-/unist-util-visit-parents-3.1.1.tgz";
        sha512 = "1KROIZWo6bcMrZEwiH2UrXDyalAa0uqzWCxCJj6lPOvTve2WkfgCytoDTPaMnodXh1WrXOq0haVYHj99ynJlsg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vfile-4.2.1" = {
      name = "vfile";
      packageName = "vfile";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile/-/vfile-4.2.1.tgz";
        sha512 = "O6AE4OskCG5S1emQ/4gl8zK586RqA3srz3nfK/Viy0UPToBc5Trp9BVFb1u0CjsKrAWwnpr4ifM/KBXPWwJbCA==";
      };
    };
    "vfile-location-3.2.0" = {
      name = "vfile-location";
      packageName = "vfile-location";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-location/-/vfile-location-3.2.0.tgz";
        sha512 = "aLEIZKv/oxuCDZ8lkJGhuhztf/BW4M+iHdCwglA/eWc+vtuRFJj8EtgceYFX4LRjOhCAAiNHsKGssC6onJ+jbA==";
      };
    };
    "vfile-message-2.0.4" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-2.0.4.tgz";
        sha512 = "DjssxRGkMvifUOJre00juHoP9DPWuzjxKuMDrhNbk2TdaYYBNMStsNhEOt3idrtI12VQYM/1+iM0KOzXi4pxwQ==";
      };
    };
    "vfile-reporter-6.0.2" = {
      name = "vfile-reporter";
      packageName = "vfile-reporter";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-reporter/-/vfile-reporter-6.0.2.tgz";
        sha512 = "GN2bH2gs4eLnw/4jPSgfBjo+XCuvnX9elHICJZjVD4+NM0nsUrMTvdjGY5Sc/XG69XVTgLwj7hknQVc6M9FukA==";
      };
    };
    "vfile-sort-2.2.2" = {
      name = "vfile-sort";
      packageName = "vfile-sort";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-sort/-/vfile-sort-2.2.2.tgz";
        sha512 = "tAyUqD2R1l/7Rn7ixdGkhXLD3zsg+XLAeUDUhXearjfIcpL1Hcsj5hHpCoy/gvfK/Ws61+e972fm0F7up7hfYA==";
      };
    };
    "vfile-statistics-1.1.4" = {
      name = "vfile-statistics";
      packageName = "vfile-statistics";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-statistics/-/vfile-statistics-1.1.4.tgz";
        sha512 = "lXhElVO0Rq3frgPvFBwahmed3X03vjPF8OcjKMy8+F1xU/3Q3QU3tKEDp743SFtb74PdF0UWpxPvtOP0GCLheA==";
      };
    };
    "wrapped-1.0.1" = {
      name = "wrapped";
      packageName = "wrapped";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrapped/-/wrapped-1.0.1.tgz";
        sha1 = "c783d9d807b273e9b01e851680a938c87c907242";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "zwitch-1.0.5" = {
      name = "zwitch";
      packageName = "zwitch";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/zwitch/-/zwitch-1.0.5.tgz";
        sha512 = "V50KMwwzqJV0NpZIZFwfOD5/lyny3WlSzRiXgA0G7VUnRlqttta1L6UQIHzd6EuBY/cHGfwTIck7w1yH6Q5zUw==";
      };
    };
  };
  args = {
    name = "remark_nix";
    packageName = "remark_nix";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@babel/code-frame-7.12.13"
      sources."@babel/helper-validator-identifier-7.12.11"
      (sources."@babel/highlight-7.13.10" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.2"
          sources."color-convert-1.9.3"
          sources."color-name-1.1.3"
          sources."has-flag-3.0.0"
          sources."supports-color-5.5.0"
        ];
      })
      sources."@types/mdast-3.0.3"
      sources."@types/unist-2.0.3"
      sources."ansi-regex-5.0.0"
      sources."ansi-styles-4.3.0"
      sources."anymatch-3.1.1"
      sources."argparse-1.0.10"
      sources."bail-1.0.5"
      sources."balanced-match-1.0.0"
      sources."binary-extensions-2.2.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."buffer-from-1.1.1"
      sources."camelcase-5.3.1"
      sources."chalk-3.0.0"
      sources."character-entities-1.2.4"
      sources."character-entities-legacy-1.1.4"
      sources."character-reference-invalid-1.1.4"
      sources."chokidar-3.5.1"
      sources."co-3.1.0"
      sources."collapse-white-space-1.0.6"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."concat-map-0.0.1"
      sources."concat-stream-2.0.0"
      sources."debug-4.3.1"
      sources."emoji-regex-8.0.0"
      sources."error-ex-1.3.2"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."extend-3.0.2"
      sources."fault-1.0.4"
      sources."figgy-pudding-3.5.2"
      sources."figures-3.2.0"
      sources."fill-range-7.0.1"
      sources."find-up-3.0.0"
      sources."format-0.2.2"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."glob-7.1.6"
      sources."glob-parent-5.1.2"
      sources."has-flag-4.0.0"
      sources."ignore-5.1.8"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."is-alphabetical-1.0.4"
      sources."is-alphanumerical-1.0.4"
      sources."is-arrayish-0.2.1"
      sources."is-binary-path-2.1.0"
      sources."is-buffer-2.0.5"
      sources."is-decimal-1.0.4"
      sources."is-empty-1.2.0"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.1"
      sources."is-hexadecimal-1.0.4"
      sources."is-number-7.0.0"
      sources."is-plain-obj-2.1.0"
      sources."js-tokens-4.0.0"
      sources."js-yaml-3.14.1"
      sources."json-parse-even-better-errors-2.3.1"
      sources."json5-2.2.0"
      sources."libnpmconfig-1.2.1"
      sources."lines-and-columns-1.1.6"
      sources."load-plugin-3.0.0"
      sources."locate-path-3.0.0"
      sources."longest-streak-2.0.4"
      sources."markdown-extensions-1.1.1"
      sources."mdast-comment-marker-1.1.2"
      sources."mdast-util-from-markdown-0.8.5"
      sources."mdast-util-heading-style-1.0.6"
      sources."mdast-util-to-markdown-0.6.5"
      sources."mdast-util-to-string-2.0.0"
      sources."micromark-2.11.4"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."ms-2.1.2"
      sources."normalize-path-3.0.0"
      sources."once-1.4.0"
      sources."p-limit-2.3.0"
      sources."p-locate-3.0.0"
      sources."p-try-2.2.0"
      sources."parse-entities-2.0.0"
      sources."parse-json-5.2.0"
      sources."path-exists-3.0.0"
      sources."path-is-absolute-1.0.1"
      sources."picomatch-2.2.2"
      sources."pluralize-8.0.0"
      sources."readable-stream-3.6.0"
      sources."readdirp-3.5.0"
      sources."remark-13.0.0"
      sources."remark-cli-9.0.0"
      sources."remark-lint-8.0.0"
      (sources."remark-lint-blockquote-indentation-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      sources."remark-lint-checkbox-character-style-3.0.0"
      sources."remark-lint-code-block-style-2.0.1"
      sources."remark-lint-definition-case-2.0.1"
      sources."remark-lint-definition-spacing-2.0.1"
      sources."remark-lint-emphasis-marker-2.0.1"
      sources."remark-lint-fenced-code-flag-2.0.1"
      sources."remark-lint-fenced-code-marker-2.0.1"
      sources."remark-lint-file-extension-1.0.5"
      sources."remark-lint-final-definition-2.1.0"
      sources."remark-lint-final-newline-1.0.5"
      sources."remark-lint-hard-break-spaces-2.0.1"
      sources."remark-lint-heading-increment-2.0.1"
      sources."remark-lint-heading-style-2.0.1"
      sources."remark-lint-link-title-style-2.0.1"
      sources."remark-lint-list-item-bullet-indent-3.0.0"
      sources."remark-lint-list-item-content-indent-2.0.1"
      sources."remark-lint-list-item-indent-2.0.1"
      sources."remark-lint-list-item-spacing-3.0.0"
      (sources."remark-lint-maximum-heading-length-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      sources."remark-lint-maximum-line-length-2.0.3"
      (sources."remark-lint-no-auto-link-without-protocol-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      sources."remark-lint-no-blockquote-without-marker-4.0.0"
      sources."remark-lint-no-consecutive-blank-lines-3.0.0"
      sources."remark-lint-no-duplicate-definitions-2.0.1"
      (sources."remark-lint-no-duplicate-headings-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      sources."remark-lint-no-emphasis-as-heading-2.0.1"
      sources."remark-lint-no-file-name-articles-1.0.5"
      sources."remark-lint-no-file-name-consecutive-dashes-1.0.5"
      sources."remark-lint-no-file-name-irregular-characters-1.0.5"
      sources."remark-lint-no-file-name-mixed-case-1.0.5"
      sources."remark-lint-no-file-name-outer-dashes-1.0.6"
      sources."remark-lint-no-heading-content-indent-3.0.0"
      (sources."remark-lint-no-heading-punctuation-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      (sources."remark-lint-no-inline-padding-3.0.0" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      (sources."remark-lint-no-literal-urls-2.0.1" // {
        dependencies = [
          sources."mdast-util-to-string-1.1.0"
        ];
      })
      sources."remark-lint-no-multiple-toplevel-headings-2.0.1"
      sources."remark-lint-no-shell-dollars-2.0.2"
      sources."remark-lint-no-shortcut-reference-image-2.0.1"
      sources."remark-lint-no-shortcut-reference-link-2.0.1"
      sources."remark-lint-no-table-indentation-3.0.0"
      sources."remark-lint-no-undefined-references-3.0.0"
      sources."remark-lint-no-unused-definitions-2.0.1"
      sources."remark-lint-ordered-list-marker-style-2.0.1"
      sources."remark-lint-ordered-list-marker-value-2.0.1"
      sources."remark-lint-rule-style-2.0.1"
      sources."remark-lint-strong-marker-2.0.1"
      sources."remark-lint-table-cell-padding-3.0.0"
      sources."remark-lint-table-pipe-alignment-2.0.1"
      sources."remark-lint-table-pipes-3.0.0"
      sources."remark-lint-unordered-list-marker-style-2.0.1"
      sources."remark-message-control-6.0.0"
      sources."remark-parse-9.0.0"
      sources."remark-preset-lint-consistent-4.0.0"
      sources."remark-preset-lint-markdown-style-guide-4.0.0"
      sources."remark-preset-lint-recommended-5.0.0"
      sources."remark-stringify-9.0.1"
      sources."repeat-string-1.6.1"
      sources."resolve-from-5.0.0"
      sources."safe-buffer-5.2.1"
      sources."sliced-1.0.1"
      sources."sprintf-js-1.0.3"
      sources."string-width-4.2.2"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.0"
      sources."supports-color-7.2.0"
      sources."text-table-0.2.0"
      sources."to-regex-range-5.0.1"
      sources."to-vfile-6.1.0"
      sources."trough-1.0.5"
      sources."typedarray-0.0.6"
      sources."unified-9.2.1"
      sources."unified-args-8.1.0"
      sources."unified-engine-8.1.0"
      sources."unified-lint-rule-1.0.6"
      sources."unified-message-control-3.0.3"
      sources."unist-util-generated-1.1.6"
      sources."unist-util-inspect-5.0.1"
      sources."unist-util-is-4.1.0"
      sources."unist-util-position-3.1.0"
      sources."unist-util-stringify-position-2.0.3"
      sources."unist-util-visit-2.0.3"
      sources."unist-util-visit-parents-3.1.1"
      sources."util-deprecate-1.0.2"
      sources."vfile-4.2.1"
      sources."vfile-location-3.2.0"
      sources."vfile-message-2.0.4"
      (sources."vfile-reporter-6.0.2" // {
        dependencies = [
          sources."has-flag-3.0.0"
          sources."supports-color-6.1.0"
        ];
      })
      sources."vfile-sort-2.2.2"
      sources."vfile-statistics-1.1.4"
      sources."wrapped-1.0.1"
      sources."wrappy-1.0.2"
      sources."zwitch-1.0.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Spell Checker for Code!";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
