# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
ls:
  .cc: snake_case
  .cmake: snake_case
  .cpp: snake_case
  .dir: regex:.github | snake_case
  .h: snake_case
  .json: regex:package-lock | snake_case
  .md: snake_case
  .sh: snake_case
  .patch: snake_case
  .txt: regex:CMakeLists | snake_case
  .nix: >
    regex:node-env | regex:node-packages | regex:python-packages | snake_case

ignore:
  - .config
  - .git
  - .gitconfig
  - .idea
  - .reuse
  - .vscode
  - LICENSES
  - build
  - build_clang
  - build_gcc
