---
dist: bionic
language:
  - cpp
  - node_js

node_js: "10"

sudo: false

cache:
  - pip
  - npm
  - bundler
  - yarn

jobs:
  include:
    - name: "Spelling by cspell"
      language: node_js
      node_js: "10"
      install:
        - npm i -g cspell
      script:
        ./ci/checks/spelling.sh

    - name: "All"
      sudo: required
      language: ruby
      rvm: 2.7
      install:
        - sudo
          ./ci/docker/docker_files/scripts/installers/checkers_dependencies.sh
      env: GO111MODULE=on
      script: ./ci/checks/all.sh

    - name: "Gcc"
      script: ./ci/builders/gcc/build.sh

    - name: "Clang"
      script: ./ci/builders/clang/build.sh

before_install: sudo chmod -R 777 "$(pwd)"
