---
dist: bionic

services:
  - docker

language: python
python: "3.8"


jobs:
  include:
    - name: "yamllint native"
      install: pip install yamllint==1.21.0
      script: yamllint -s .
    - name: "yamllint in docker"
      install: docker pull melg8/yamllint:0.0.1
      script: docker run --rm -i -v "$(pwd)":/home/user melg8/yamllint:0.0.1 "yamllint" "-s" "."
