# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
extends: default
rules:
  line-length:
    max: 80
  comments:
    min-spaces-from-content: 1
  braces: disable
  indentation: disable # Cause prettier already better at fixing indentation.
